# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_design/system_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design || ORIG_REF_NAME==system_design} -quiet] -quiet

# IP: bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_processing_system7_0_0 || ORIG_REF_NAME==system_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_system_ila_0_0/system_design_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_system_ila_0_0 || ORIG_REF_NAME==system_design_system_ila_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_rst_ps7_0_100M_0/system_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_axi_smc_0/system_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_axi_smc_0 || ORIG_REF_NAME==system_design_axi_smc_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xbar_3/system_design_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xbar_3 || ORIG_REF_NAME==system_design_xbar_3} -quiet] -quiet

# IP: bd/system_design/ip/system_design_ps7_0_axi_periph_0/system_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xfft_0_0/system_design_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xfft_0_0 || ORIG_REF_NAME==system_design_xfft_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_DMA_DATA_0/system_design_DMA_DATA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_DMA_DATA_0 || ORIG_REF_NAME==system_design_DMA_DATA_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_axi_dma_0_0/system_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_axi_dma_0_0 || ORIG_REF_NAME==system_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_xlconcat_0_0/system_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_xlconcat_0_0 || ORIG_REF_NAME==system_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_axi_intc_0_0/system_design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_axi_intc_0_0 || ORIG_REF_NAME==system_design_axi_intc_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_pc_0/system_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_pc_0 || ORIG_REF_NAME==system_design_auto_pc_0} -quiet] -quiet

# XDC: bd/system_design/system_design_ooc.xdc
