# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/hdl/system_design_wrapper.vhd
add_files C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/system_design.bd
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/system_design_system_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/bd_0/ip/ip_0/bd_db0b_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_system_ila_0_0/bd_0/bd_db0b_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_rst_ps7_0_100M_0/system_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_rst_ps7_0_100M_0/system_design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_rst_ps7_0_100M_0/system_design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_2/bd_4b57_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_3/bd_4b57_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_4/bd_4b57_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_5/bd_4b57_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_6/bd_4b57_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_10/bd_4b57_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_11/bd_4b57_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_12/bd_4b57_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_16/bd_4b57_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_17/bd_4b57_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_18/bd_4b57_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_19/bd_4b57_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_23/bd_4b57_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_24/bd_4b57_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_25/bd_4b57_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_26/bd_4b57_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_27/bd_4b57_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_28/bd_4b57_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_29/bd_4b57_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_30/bd_4b57_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_31/bd_4b57_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xbar_3/system_design_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xfft_0_0/system_design_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_DMA_DATA_0/system_design_DMA_DATA_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_DMA_DATA_0/system_design_DMA_DATA_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_DMA_DATA_0/system_design_DMA_DATA_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_dma_0_0/system_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_dma_0_0/system_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_dma_0_0/system_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_intc_0_0/system_design_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_intc_0_0/system_design_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_intc_0_0/system_design_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_auto_pc_0/system_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/system_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_design_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_design_wrapper_utilization_synth.rpt -pb system_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
