# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xbar_3/system_design_xbar_3.xci
# IP: The module: 'system_design_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xbar_3/system_design_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_design_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xbar_3/system_design_xbar_3.xci
# IP: The module: 'system_design_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_xbar_3/system_design_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_design_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
