# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/system_design_axi_smc_0.xci
# IP: The module: 'system_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/bd_4b57.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_0/bd_4b57_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_2/bd_4b57_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_3/bd_4b57_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_4/bd_4b57_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_5/bd_4b57_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_6/bd_4b57_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_7/bd_4b57_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_8/bd_4b57_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_9/bd_4b57_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_10/bd_4b57_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_11/bd_4b57_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_12/bd_4b57_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_13/bd_4b57_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_14/bd_4b57_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_15/bd_4b57_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_16/bd_4b57_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_17/bd_4b57_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_18/bd_4b57_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_19/bd_4b57_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_20/bd_4b57_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_21/bd_4b57_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_22/bd_4b57_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_23/bd_4b57_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_24/bd_4b57_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_25/bd_4b57_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_26/bd_4b57_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_27/bd_4b57_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_28/bd_4b57_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_29/bd_4b57_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_30/bd_4b57_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_31/bd_4b57_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_32/bd_4b57_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_2/bd_4b57_arsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_3/bd_4b57_rsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_4/bd_4b57_awsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_5/bd_4b57_wsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_6/bd_4b57_bsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_10/bd_4b57_s00a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_11/bd_4b57_sarn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_12/bd_4b57_srn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_16/bd_4b57_s01a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_17/bd_4b57_sawn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_18/bd_4b57_swn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_19/bd_4b57_sbn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_23/bd_4b57_s02a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_24/bd_4b57_sarn_1_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_25/bd_4b57_srn_1_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_26/bd_4b57_m00s2a_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_27/bd_4b57_m00arn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_28/bd_4b57_m00rn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_29/bd_4b57_m00awn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_30/bd_4b57_m00wn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_31/bd_4b57_m00bn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/system_design_axi_smc_0.xci
# IP: The module: 'system_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/bd_4b57.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_0/bd_4b57_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_2/bd_4b57_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_3/bd_4b57_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_4/bd_4b57_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_5/bd_4b57_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_6/bd_4b57_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_7/bd_4b57_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_8/bd_4b57_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_9/bd_4b57_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_10/bd_4b57_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_11/bd_4b57_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_12/bd_4b57_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_13/bd_4b57_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_14/bd_4b57_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_15/bd_4b57_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_16/bd_4b57_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_17/bd_4b57_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_18/bd_4b57_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_19/bd_4b57_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_20/bd_4b57_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_21/bd_4b57_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_22/bd_4b57_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_23/bd_4b57_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_24/bd_4b57_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_25/bd_4b57_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_26/bd_4b57_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_27/bd_4b57_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_28/bd_4b57_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_29/bd_4b57_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_30/bd_4b57_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_31/bd_4b57_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_32/bd_4b57_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_1/bd_4b57_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_2/bd_4b57_arsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_3/bd_4b57_rsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_4/bd_4b57_awsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_5/bd_4b57_wsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_6/bd_4b57_bsw_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_10/bd_4b57_s00a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_11/bd_4b57_sarn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_12/bd_4b57_srn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_16/bd_4b57_s01a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_17/bd_4b57_sawn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_18/bd_4b57_swn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_19/bd_4b57_sbn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_23/bd_4b57_s02a2s_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_24/bd_4b57_sarn_1_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_25/bd_4b57_srn_1_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_26/bd_4b57_m00s2a_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_27/bd_4b57_m00arn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_28/bd_4b57_m00rn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_29/bd_4b57_m00awn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_30/bd_4b57_m00wn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/bd_0/ip/ip_31/bd_4b57_m00bn_0_ooc.xdc

# XDC: c:/Users/lukes/Documents/Final_Year_Project/Architecture/FFT_axi/vhdl/xilinxprj/project_1.srcs/sources_1/bd/system_design/ip/system_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
